//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcmeCurso.UI.MVC.WcfInscricaoService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WcfInscricaoService.IInscricaoService")]
    public interface IInscricaoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInscricaoService/Add", ReplyAction="http://tempuri.org/IInscricaoService/AddResponse")]
        void Add(AcmeCurso.Domain.Inscricao item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInscricaoService/Add", ReplyAction="http://tempuri.org/IInscricaoService/AddResponse")]
        System.Threading.Tasks.Task AddAsync(AcmeCurso.Domain.Inscricao item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInscricaoService/Delete", ReplyAction="http://tempuri.org/IInscricaoService/DeleteResponse")]
        void Delete(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInscricaoService/Delete", ReplyAction="http://tempuri.org/IInscricaoService/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInscricaoService/Update", ReplyAction="http://tempuri.org/IInscricaoService/UpdateResponse")]
        void Update(AcmeCurso.Domain.Inscricao item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInscricaoService/Update", ReplyAction="http://tempuri.org/IInscricaoService/UpdateResponse")]
        System.Threading.Tasks.Task UpdateAsync(AcmeCurso.Domain.Inscricao item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInscricaoService/GetById", ReplyAction="http://tempuri.org/IInscricaoService/GetByIdResponse")]
        AcmeCurso.Domain.Inscricao GetById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInscricaoService/GetById", ReplyAction="http://tempuri.org/IInscricaoService/GetByIdResponse")]
        System.Threading.Tasks.Task<AcmeCurso.Domain.Inscricao> GetByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInscricaoService/GetAll", ReplyAction="http://tempuri.org/IInscricaoService/GetAllResponse")]
        AcmeCurso.Domain.Inscricao[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInscricaoService/GetAll", ReplyAction="http://tempuri.org/IInscricaoService/GetAllResponse")]
        System.Threading.Tasks.Task<AcmeCurso.Domain.Inscricao[]> GetAllAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IInscricaoServiceChannel : AcmeCurso.UI.MVC.WcfInscricaoService.IInscricaoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InscricaoServiceClient : System.ServiceModel.ClientBase<AcmeCurso.UI.MVC.WcfInscricaoService.IInscricaoService>, AcmeCurso.UI.MVC.WcfInscricaoService.IInscricaoService {
        
        public InscricaoServiceClient() {
        }
        
        public InscricaoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InscricaoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InscricaoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InscricaoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Add(AcmeCurso.Domain.Inscricao item) {
            base.Channel.Add(item);
        }
        
        public System.Threading.Tasks.Task AddAsync(AcmeCurso.Domain.Inscricao item) {
            return base.Channel.AddAsync(item);
        }
        
        public void Delete(int id) {
            base.Channel.Delete(id);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(int id) {
            return base.Channel.DeleteAsync(id);
        }
        
        public void Update(AcmeCurso.Domain.Inscricao item) {
            base.Channel.Update(item);
        }
        
        public System.Threading.Tasks.Task UpdateAsync(AcmeCurso.Domain.Inscricao item) {
            return base.Channel.UpdateAsync(item);
        }
        
        public AcmeCurso.Domain.Inscricao GetById(int id) {
            return base.Channel.GetById(id);
        }
        
        public System.Threading.Tasks.Task<AcmeCurso.Domain.Inscricao> GetByIdAsync(int id) {
            return base.Channel.GetByIdAsync(id);
        }
        
        public AcmeCurso.Domain.Inscricao[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<AcmeCurso.Domain.Inscricao[]> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
    }
}
