//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcmeCurso.UI.MVC.WcfCursoService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WcfCursoService.ICursoService")]
    public interface ICursoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICursoService/Add", ReplyAction="http://tempuri.org/ICursoService/AddResponse")]
        void Add(AcmeCurso.Domain.Curso item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICursoService/Add", ReplyAction="http://tempuri.org/ICursoService/AddResponse")]
        System.Threading.Tasks.Task AddAsync(AcmeCurso.Domain.Curso item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICursoService/Delete", ReplyAction="http://tempuri.org/ICursoService/DeleteResponse")]
        void Delete(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICursoService/Delete", ReplyAction="http://tempuri.org/ICursoService/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICursoService/Update", ReplyAction="http://tempuri.org/ICursoService/UpdateResponse")]
        void Update(AcmeCurso.Domain.Curso item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICursoService/Update", ReplyAction="http://tempuri.org/ICursoService/UpdateResponse")]
        System.Threading.Tasks.Task UpdateAsync(AcmeCurso.Domain.Curso item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICursoService/GetById", ReplyAction="http://tempuri.org/ICursoService/GetByIdResponse")]
        AcmeCurso.Domain.Curso GetById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICursoService/GetById", ReplyAction="http://tempuri.org/ICursoService/GetByIdResponse")]
        System.Threading.Tasks.Task<AcmeCurso.Domain.Curso> GetByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICursoService/GetAll", ReplyAction="http://tempuri.org/ICursoService/GetAllResponse")]
        AcmeCurso.Domain.Curso[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICursoService/GetAll", ReplyAction="http://tempuri.org/ICursoService/GetAllResponse")]
        System.Threading.Tasks.Task<AcmeCurso.Domain.Curso[]> GetAllAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICursoServiceChannel : AcmeCurso.UI.MVC.WcfCursoService.ICursoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CursoServiceClient : System.ServiceModel.ClientBase<AcmeCurso.UI.MVC.WcfCursoService.ICursoService>, AcmeCurso.UI.MVC.WcfCursoService.ICursoService {
        
        public CursoServiceClient() {
        }
        
        public CursoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CursoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CursoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CursoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Add(AcmeCurso.Domain.Curso item) {
            base.Channel.Add(item);
        }
        
        public System.Threading.Tasks.Task AddAsync(AcmeCurso.Domain.Curso item) {
            return base.Channel.AddAsync(item);
        }
        
        public void Delete(int id) {
            base.Channel.Delete(id);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(int id) {
            return base.Channel.DeleteAsync(id);
        }
        
        public void Update(AcmeCurso.Domain.Curso item) {
            base.Channel.Update(item);
        }
        
        public System.Threading.Tasks.Task UpdateAsync(AcmeCurso.Domain.Curso item) {
            return base.Channel.UpdateAsync(item);
        }
        
        public AcmeCurso.Domain.Curso GetById(int id) {
            return base.Channel.GetById(id);
        }
        
        public System.Threading.Tasks.Task<AcmeCurso.Domain.Curso> GetByIdAsync(int id) {
            return base.Channel.GetByIdAsync(id);
        }
        
        public AcmeCurso.Domain.Curso[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<AcmeCurso.Domain.Curso[]> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
    }
}
