//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcmeCurso.UI.MVC.WcfEstudanteService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WcfEstudanteService.IEstudanteService")]
    public interface IEstudanteService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEstudanteService/Add", ReplyAction="http://tempuri.org/IEstudanteService/AddResponse")]
        void Add(AcmeCurso.Domain.Estudante item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEstudanteService/Add", ReplyAction="http://tempuri.org/IEstudanteService/AddResponse")]
        System.Threading.Tasks.Task AddAsync(AcmeCurso.Domain.Estudante item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEstudanteService/Delete", ReplyAction="http://tempuri.org/IEstudanteService/DeleteResponse")]
        void Delete(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEstudanteService/Delete", ReplyAction="http://tempuri.org/IEstudanteService/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEstudanteService/Update", ReplyAction="http://tempuri.org/IEstudanteService/UpdateResponse")]
        void Update(AcmeCurso.Domain.Estudante item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEstudanteService/Update", ReplyAction="http://tempuri.org/IEstudanteService/UpdateResponse")]
        System.Threading.Tasks.Task UpdateAsync(AcmeCurso.Domain.Estudante item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEstudanteService/GetById", ReplyAction="http://tempuri.org/IEstudanteService/GetByIdResponse")]
        AcmeCurso.Domain.Estudante GetById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEstudanteService/GetById", ReplyAction="http://tempuri.org/IEstudanteService/GetByIdResponse")]
        System.Threading.Tasks.Task<AcmeCurso.Domain.Estudante> GetByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEstudanteService/GetAll", ReplyAction="http://tempuri.org/IEstudanteService/GetAllResponse")]
        AcmeCurso.Domain.Estudante[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEstudanteService/GetAll", ReplyAction="http://tempuri.org/IEstudanteService/GetAllResponse")]
        System.Threading.Tasks.Task<AcmeCurso.Domain.Estudante[]> GetAllAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEstudanteServiceChannel : AcmeCurso.UI.MVC.WcfEstudanteService.IEstudanteService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EstudanteServiceClient : System.ServiceModel.ClientBase<AcmeCurso.UI.MVC.WcfEstudanteService.IEstudanteService>, AcmeCurso.UI.MVC.WcfEstudanteService.IEstudanteService {
        
        public EstudanteServiceClient() {
        }
        
        public EstudanteServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EstudanteServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EstudanteServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EstudanteServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Add(AcmeCurso.Domain.Estudante item) {
            base.Channel.Add(item);
        }
        
        public System.Threading.Tasks.Task AddAsync(AcmeCurso.Domain.Estudante item) {
            return base.Channel.AddAsync(item);
        }
        
        public void Delete(int id) {
            base.Channel.Delete(id);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(int id) {
            return base.Channel.DeleteAsync(id);
        }
        
        public void Update(AcmeCurso.Domain.Estudante item) {
            base.Channel.Update(item);
        }
        
        public System.Threading.Tasks.Task UpdateAsync(AcmeCurso.Domain.Estudante item) {
            return base.Channel.UpdateAsync(item);
        }
        
        public AcmeCurso.Domain.Estudante GetById(int id) {
            return base.Channel.GetById(id);
        }
        
        public System.Threading.Tasks.Task<AcmeCurso.Domain.Estudante> GetByIdAsync(int id) {
            return base.Channel.GetByIdAsync(id);
        }
        
        public AcmeCurso.Domain.Estudante[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<AcmeCurso.Domain.Estudante[]> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
    }
}
